### ISSUE TITLE
[Scene] ScheduleListScene

### ISSUE THREAD

**Issue by Judy-999** [Judy-999/ios-wanted-PersonalScheduler#2]
## Description
스케줄 리스트를 보여주는 화면 구현

![image](https://user-images.githubusercontent.com/102353787/211436052-2db6ce59-85f5-4199-8882-e118114746ce.png)

## TODO
- [x] TableView - grouped
- [x] 섹션에 날짜 표시
- [x] 알림 여부에 따라 표시 변경 (알림 예정/ 알림 울림/ 알림 거부)
- [x] 날짜 지남 여부에 따라 하이라이트 변경 (날짜 지남 - 회색, 날짜 지나지 않음 - 연두)
- [x]  스와이프 삭제
- [x] 일정 없을 때 화면 
- [x] 셀에 시작 시간 표시
