### ISSUE TITLE
[Feat] FirebaseManager

### ISSUE THREAD

**Issue by Judy-999** [Judy-999/ios-wanted-PersonalScheduler#3]
## Description
스케줄 정보를 저장하는 Firebase 사용 객체 구현

## TODO
- [x] Firestore dependency 추가
- [x] FirestoreManager에 CURD 구현
- [x] Schedule Entity 생성
- [x] ScheduleFirestoreUseCase
